name: Preview

on:
  pull_request:
    branches:
    paths:
      - 'src/webapp/**'
      - '.github/workflows/preview-webapp.yml'

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            yarn
            REACT_APP_FIREBASE_KEY=${{ secrets.REACT_APP_FIREBASE_KEY }} yarn build
          dist: 'src/webapp/build'
