name: Preview

on:
  pull_request:
    branches:
    paths:
      - 'src/webapp/**'
      - '.github/workflows/preview-webapp.yml'

jobs:
  webaoo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--build-env REACT_APP_FIREBASE_KEY=${{ secrets.FIREBASE_KEY }}'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./src/webapp