name: Preview

on:
  pull_request:
    branches:
    paths:
      - 'src/webapp/**'
      - '.github/workflows/preview-webapp.yml'

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_WEBAPP_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_WEBAPP_PROJECT_ID}}