name: Preview

on:
  pull_request:
    branches:
    paths:
      - 'packages/ui/**'
      - '.github/workflows/preview-storybook.yml'

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            yarn
            yarn build:storybook
          dist: 'packages/ui/storybook-static'