name: Preview

on:
  pull_request:
    branches:
    paths:
      - "src/webapp/**"
      - ".github/workflows/preview-webapp.yml"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Builds
        run: yarn && yarn build

      - name: Deploys
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: small-ads-39e36
